// Auto-generated by scripts/gen_firmware_version.py — do not edit.
#ifndef FIRMWARE_VERSION_GEN_H
#define FIRMWARE_VERSION_GEN_H

#define FW_PRODUCT_NAME             "stm32-app"
#define FW_VERSION_MAJOR            1
#define FW_VERSION_MINOR            0
#define FW_VERSION_PATCH            0
#define FW_VERSION_PRERELEASE       ""
#define FW_VERSION_STRING           "1.0.0"
#define FW_VERSION_STRING_FULL      "1.0.0+unknown-dirty"
#define FW_VERSION_TAG              "v1.0.0"
#define FW_VERSION_NUM              65536U
#define FW_GIT_SHA_SHORT            "unknown"
#define FW_GIT_DESCRIBE             "unknown"
#define FW_GIT_BRANCH               "unknown"
#define FW_GIT_DIRTY                1

#endif
