#!/usr/bin/env python3
# Generates firmware_version_gen.h, build/version.mk, build/version.env from version.toml + git.

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


def parse_version_toml(path: Path) -> dict[str, str | int]:
    text = path.read_text(encoding="utf-8")
    section = "firmware"
    data: dict[str, str | int] = {"name": "firmware"}

    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip()
            continue
        if section != "firmware":
            continue
        match = re.match(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$", line)
        if not match:
            continue
        key, value = match.group(1), match.group(2).strip()
        if value.startswith('"') and value.endswith('"'):
            data[key] = value[1:-1]
        elif value.startswith("'") and value.endswith("'"):
            data[key] = value[1:-1]
        else:
            data[key] = int(value)

    for key in ("major", "minor", "patch"):
        if key not in data:
            raise ValueError(f"version.toml missing firmware.{key}")

    return data


def run_git(repo_root: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=repo_root,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def git_info(repo_root: Path) -> dict[str, str | int]:
    sha = run_git(repo_root, "rev-parse", "--short", "HEAD") or "unknown"
    dirty = 0
    status = run_git(repo_root, "status", "--porcelain")
    if status:
        dirty = 1
    describe = run_git(repo_root, "describe", "--tags", "--always", "--dirty") or sha
    branch = run_git(repo_root, "rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    return {
        "git_sha_short": sha,
        "git_describe": describe,
        "git_branch": branch,
        "git_dirty": dirty,
    }


def version_string(major: int, minor: int, patch: int, prerelease: str | None) -> str:
    base = f"{major}.{minor}.{patch}"
    if prerelease:
        return f"{base}-{prerelease}"
    return base


def version_string_full(base: str, git: dict[str, str | int]) -> str:
    suffix = str(git["git_sha_short"])
    if git["git_dirty"]:
        suffix += "-dirty"
    return f"{base}+{suffix}"


def packed_version(major: int, minor: int, patch: int) -> int:
    return ((major & 0xFF) << 16) | ((minor & 0xFF) << 8) | (patch & 0xFF)


def write_header(path: Path, meta: dict) -> None:
    content = f"""// Auto-generated by scripts/gen_firmware_version.py — do not edit.
#ifndef FIRMWARE_VERSION_GEN_H
#define FIRMWARE_VERSION_GEN_H

#define FW_PRODUCT_NAME             "{meta['name']}"
#define FW_VERSION_MAJOR            {meta['major']}
#define FW_VERSION_MINOR            {meta['minor']}
#define FW_VERSION_PATCH            {meta['patch']}
#define FW_VERSION_PRERELEASE       "{meta['prerelease']}"
#define FW_VERSION_STRING           "{meta['version_string']}"
#define FW_VERSION_STRING_FULL      "{meta['version_string_full']}"
#define FW_VERSION_TAG              "{meta['version_tag']}"
#define FW_VERSION_NUM              {meta['version_num']}U
#define FW_GIT_SHA_SHORT            "{meta['git_sha_short']}"
#define FW_GIT_DESCRIBE             "{meta['git_describe']}"
#define FW_GIT_BRANCH               "{meta['git_branch']}"
#define FW_GIT_DIRTY                {meta['git_dirty']}

#endif
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def write_makefile(path: Path, meta: dict) -> None:
    lines = [
        "# Auto-generated by scripts/gen_firmware_version.py — do not edit.",
        f"FW_PRODUCT_NAME := {meta['name']}",
        f"FW_VERSION_MAJOR := {meta['major']}",
        f"FW_VERSION_MINOR := {meta['minor']}",
        f"FW_VERSION_PATCH := {meta['patch']}",
        f"FW_VERSION_STRING := {meta['version_string']}",
        f"FW_VERSION_STRING_FULL := {meta['version_string_full']}",
        f"FW_VERSION_TAG := {meta['version_tag']}",
        f"FW_VERSION_NUM := {meta['version_num']}",
        f"FW_GIT_SHA_SHORT := {meta['git_sha_short']}",
        f"FW_GIT_DESCRIBE := {meta['git_describe']}",
        f"FW_GIT_BRANCH := {meta['git_branch']}",
        f"FW_GIT_DIRTY := {meta['git_dirty']}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_env(path: Path, meta: dict) -> None:
    lines = [
        "# Auto-generated by scripts/gen_firmware_version.py — do not edit.",
        f"FW_PRODUCT_NAME={meta['name']}",
        f"FW_VERSION_MAJOR={meta['major']}",
        f"FW_VERSION_MINOR={meta['minor']}",
        f"FW_VERSION_PATCH={meta['patch']}",
        f"FW_VERSION_STRING={meta['version_string']}",
        f"FW_VERSION_STRING_FULL={meta['version_string_full']}",
        f"FW_VERSION_TAG={meta['version_tag']}",
        f"FW_VERSION_NUM={meta['version_num']}",
        f"FW_GIT_SHA_SHORT={meta['git_sha_short']}",
        f"FW_GIT_DESCRIBE={meta['git_describe']}",
        f"FW_GIT_BRANCH={meta['git_branch']}",
        f"FW_GIT_DIRTY={meta['git_dirty']}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def build_meta(repo_root: Path, version_file: Path) -> dict:
    cfg = parse_version_toml(version_file)
    major = int(cfg["major"])
    minor = int(cfg["minor"])
    patch = int(cfg["patch"])
    prerelease = str(cfg.get("prerelease", "") or "")
    name = str(cfg.get("name", "firmware"))
    ver = version_string(major, minor, patch, prerelease or None)
    git = git_info(repo_root)
    ver_full = version_string_full(ver, git)

    return {
        "name": name,
        "major": major,
        "minor": minor,
        "patch": patch,
        "prerelease": prerelease,
        "version_string": ver,
        "version_string_full": ver_full,
        "version_tag": f"v{ver}",
        "version_num": packed_version(major, minor, patch),
        **git,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate firmware version artifacts.")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--version-file",
        type=Path,
        default=None,
        help="Path to version.toml (default: <root>/version.toml)",
    )
    args = parser.parse_args()
    repo_root = args.root.resolve()
    version_file = (args.version_file or repo_root / "version.toml").resolve()

    if not version_file.is_file():
        print(f"error: {version_file} not found", file=sys.stderr)
        return 1

    meta = build_meta(repo_root, version_file)
    write_header(repo_root / "Application" / "product" / "Inc" / "firmware_version_gen.h", meta)
    write_makefile(repo_root / "build" / "version.mk", meta)
    write_env(repo_root / "build" / "version.env", meta)

    print(
        f"firmware version {meta['version_string_full']} "
        f"(tag {meta['version_tag']}, num 0x{meta['version_num']:06X})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
